frontend:
  build: ../site/
  container_name: site
  environment:
    - SERVICE_HOST=0.0.0.0
    - SERVICE_PORT=20000
    - PROXY_HOST=192.168.99.100
    - frontend_PORT=10000
    - addition_PORT=10001
  ports:
    - 10000:20000
addition:
  build: ../addition/
  container_name: addition
  environment:
    - SERVICE_HOST=0.0.0.0
    - SERVICE_PORT=20001
    - PROXY_HOST=192.168.99.100
    - frontend_PORT=10000
    - addition_PORT=10001
  ports:
    - 10001:20001
